version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: Zookeeper
    networks: 
      - compose-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: Kafka
    networks: 
      - compose-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: KafkaDrop
    networks: 
      - compose-network
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  
  mongo:
    image: mongo
    container_name: Mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: QliIZ6xIHH3wYveK
    ports:
      - "27017:27017"
    expose:
      - "27017"  
    volumes:
      - mongodata:/data/db
    networks: 
      - compose-network
  
  mysql:
     image: mysql:5.7
     container_name: MySql
     environment:
       MYSQL_ROOT_PASSWORD: "Hkm25gRhan19JGWq"
     ports:
       - "3306:3306" 
     expose:
       - "3306"
     networks: 
      - compose-network  
     volumes:
       - mysqldata:/var/lib/mysql
     restart: always 
  
  poc.puc.modulo.associado.api:
    image: ${DOCKER_REGISTRY-}pucpocmoduloassociadowebapi
    container_name: associado.webapi
    depends_on: 
        - mysql
        - mongo
    build:
      context: .
      dockerfile: DockerfileAssociado
    networks: 
      - compose-network
    ports:
      - "20000:80"

  poc.puc.modulo.conveniado.api:
    image: ${DOCKER_REGISTRY-}pucpocmoduloconveniadowebapi
    container_name: conveniado.webapi
    depends_on: 
        - mysql
        - mongo
    build:
      context: .
      dockerfile: DockerfileConveniado
    networks: 
      - compose-network
    ports:
      - "20001:80"

volumes:
    mysqldata:
    mongodata:
    
networks: 
  compose-network:
    driver: bridge  
      