// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using puc.poc.modulo.agenda.repositorio.writemodel;

namespace puc.poc.modulo.agenda.repositorio.writemodel.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.Agendamento", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssociadoUniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConveniadoUniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EspecialidadeUniqueId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UniqueId");

                    b.HasIndex("AssociadoUniqueId");

                    b.HasIndex("ConveniadoUniqueId");

                    b.HasIndex("EspecialidadeUniqueId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.Associado", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UniqueId");

                    b.ToTable("Associados");
                });

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.Conveniado", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UniqueId");

                    b.ToTable("Conveniados");
                });

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.EspecialidadeConveniado", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TempoDuracao")
                        .HasColumnType("int");

                    b.HasKey("UniqueId");

                    b.ToTable("EspecialidadesConveniado");
                });

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.Agendamento", b =>
                {
                    b.HasOne("puc.poc.modulo.agenda.dominio.WriteModel.Associado", "Associado")
                        .WithMany("Agendamentos")
                        .HasForeignKey("AssociadoUniqueId");

                    b.HasOne("puc.poc.modulo.agenda.dominio.WriteModel.Conveniado", "Conveniado")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ConveniadoUniqueId");

                    b.HasOne("puc.poc.modulo.agenda.dominio.WriteModel.EspecialidadeConveniado", "Especialidade")
                        .WithMany("Agendamentos")
                        .HasForeignKey("EspecialidadeUniqueId");

                    b.Navigation("Associado");

                    b.Navigation("Conveniado");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.Associado", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.Conveniado", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("puc.poc.modulo.agenda.dominio.WriteModel.EspecialidadeConveniado", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
