// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using puc.poc.modulo.servico.repositorio.writemodel;

namespace puc.poc.modulo.servico.repositorio.writemodel.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220206142926_InicialMigration")]
    partial class InicialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("puc.poc.modulo.servico.dominio.WriteModel.Associado", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ModeloPlano")
                        .HasColumnType("int");

                    b.Property<int>("TipoPlano")
                        .HasColumnType("int");

                    b.HasKey("UniqueId");

                    b.ToTable("Associados");
                });

            modelBuilder.Entity("puc.poc.modulo.servico.dominio.WriteModel.OrdemServico", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssociadoUniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ServicoUniqueId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UniqueId");

                    b.HasIndex("AssociadoUniqueId");

                    b.HasIndex("ServicoUniqueId");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("puc.poc.modulo.servico.dominio.WriteModel.Servico", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("ValorCobrado")
                        .HasColumnType("double");

                    b.Property<double>("ValorPago")
                        .HasColumnType("double");

                    b.HasKey("UniqueId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("puc.poc.modulo.servico.dominio.WriteModel.OrdemServico", b =>
                {
                    b.HasOne("puc.poc.modulo.servico.dominio.WriteModel.Associado", "Associado")
                        .WithMany("Servicos")
                        .HasForeignKey("AssociadoUniqueId");

                    b.HasOne("puc.poc.modulo.servico.dominio.WriteModel.Servico", "Servico")
                        .WithMany("Servicos")
                        .HasForeignKey("ServicoUniqueId");

                    b.Navigation("Associado");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("puc.poc.modulo.servico.dominio.WriteModel.Associado", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("puc.poc.modulo.servico.dominio.WriteModel.Servico", b =>
                {
                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
